

名称：快手视频浏览

在：
  工作流程调度：
  时间表：
     -的cron的： '* / 30 0,2,4,6,8,10,12 * * *'
  观看：
    类型：开始
职位：
  建立：
    运行：ubuntu-latest
    如果：github.event.repository.owner.id == github.event.sender.id
    环保：
        KUAISHOUMV：$ {{secrets.KUAISHOUMV}}
        TZ：亚洲/上海
    步骤：
      -名称：结帐
        运行：|
          git clone https://github.com/Sunert/Scripts.git〜/脚本
      -名称：使用Node.js 12.x
        用途：动作/设置节点@ v1
        与：
          官方版本：12.x
      -名称：npm安装
        运行：|
          cd〜 /脚本
          npm安装
      -名称：'运行【快手视频】'
        如果：env.KUAISHOUMV
        运行：|
          cd〜 /脚本
          官员Task / Auto_Kuaishou.js
        环保：
          PUSH_KEY：$ {{secrets.PUSH_KEY}}
          TG_BOT_TOKEN：$ {{secrets.TG_BOT_TOKEN}}
          TG_USER_ID：$ {{secrets.TG_USER_ID}}
